sudo: required
language: generic
dist: xenial 

addons:
  apt:
    packages:
      libc6-i386
      libspeexdsp-dev
      libsamplerate0-dev
      sox

install:
    - export LPCNETDIR=${PWD}
    - export BUILDDIR=${PWD}/build_linux

script:
    - mkdir -p $BUILDDIR
    - cd $BUILDDIR 
    - cmake ..
    - make
    - cd src
    - sox ../../wav/wia.wav -t raw -r 16000 - | ./lpcnet_enc -s | ./lpcnet_dec -s > /dev/null
    
